language: cpp
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:yubico/stable
  - sudo add-apt-repository -y ppa:beineri/opt-qt57-trusty
  - sudo apt-get update
  - sudo apt-get install -y swig libpcsclite-dev libykpers-1-dev libu2f-host-dev qt57base qt57declarative qt57quickcontrols g++
  - source /opt/qt57/bin/qt57-env.sh

script:
  - qmake
  - make
