language: cpp
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:yubico/stable
  - sudo add-apt-repository -y ppa:beineri/opt-qt57-trusty
  - sudo apt-get update

install:
  - sudo apt-get install -y libykpers-1-dev libu2f-host-dev 
  - sudo apt-get install -y qt57base qt57declarative qt57quickcontrols qt57svg g++ swig 
  - sudo apt-get install -y libpcsclite-dev python3-dev python-pyscard python3-pip pcscd
  - source /opt/qt57/bin/qt57-env.sh
  - cd vendor/pyotherside
  - qmake
  - make
  - sudo make install
  - cd ../..
  - sudo pip3 install vendor/yubikey-manager

script:
  - qmake
  - make
