language: cpp

os:
  - linux
  - osx

dist: trusty

sudo: required

before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]
  then
    sudo add-apt-repository -y ppa:yubico/stable
    sudo add-apt-repository -y ppa:beineri/opt-qt57-trusty
    sudo apt-get update
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]
  then
    export MACOSX_DEPLOYMENT_TARGET=10.9
    brew update
    git clone https://github.com/iltommi/macdeployqtfix.git
  fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get install -y libykpers-1-dev libu2f-host-dev 
      sudo apt-get install -y qt57base qt57declarative qt57quickcontrols qt57svg g++ swig 
      sudo apt-get install -y libpcsclite-dev python3-dev python-pyscard python3-pip pcscd
      source /opt/qt57/bin/qt57-env.sh
      cd vendor/pyotherside
      qmake
      make
      sudo make install
      cd ../..
      sudo pip3 install vendor/yubikey-manager
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew install qt5 swig
      brew link qt5 -f
      brew install ykpers libyubikey hidapi libu2f-host libusb
      brew install pyenv
      env PYTHON_CONFIGURE_OPTS="--enable-framework CC=clang" pyenv install 3.5.2
      eval "$(pyenv init -)"
      pyenv global system 3.5.2 
      cd vendor/pyotherside
      echo "DEFINES += QT_NO_DEBUG_OUTPUT" >> src/src.pro
      qmake
      make
      sudo make install
      cd ../..
      sudo pip3 install vendor/yubikey-manager
    fi

script:
  - qmake
  - make
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      macdeployqt ykman-gui/ykman-gui.app/ -qmldir=ykman-gui/
      find /usr/local/Cellar/json-c/ -name '*.dylib' -exec cp '{}' ykman-gui/ykman-gui.app/Contents/Frameworks/ ';'
      find /usr/local/Cellar/ykpers/ -name '*.dylib' -exec cp '{}' ykman-gui/ykman-gui.app/Contents/Frameworks/ ';'
      find /usr/local/Cellar/libyubikey/ -name '*.dylib' -exec cp '{}' ykman-gui/ykman-gui.app/Contents/Frameworks/ ';'
      find /usr/local/Cellar/hidapi/ -name '*.dylib' -exec cp '{}' ykman-gui/ykman-gui.app/Contents/Frameworks/ ';'
      find /usr/local/Cellar/libu2f-host/ -name '*.dylib' -exec cp '{}' ykman-gui/ykman-gui.app/Contents/Frameworks/ ';'
      find /usr/local/Cellar/libusb/ -name '*.dylib' -exec cp '{}' ykman-gui/ykman-gui.app/Contents/Frameworks/ ';'
      cp ykman-cli/ykman ykman-gui/ykman-gui.app/Contents/MacOS/
      cp -a ~/.pyenv/versions/3.5.2/Python.framework ykman-gui/ykman-gui.app/Contents/Frameworks/
      sudo find ykman-gui/ykman-gui.app/Contents/Frameworks/Python.framework -name '*.pyc' -delete
      sudo find ykman-gui/ykman-gui.app/Contents/Frameworks/Python.framework -name '__pycache__' -delete
      sudo python macdeployqtfix/macdeployqtfix.py ykman-gui/ykman-gui.app/Contents/MacOS/ykman-gui /usr/local
      sudo python macdeployqtfix/macdeployqtfix.py ykman-gui/ykman-gui.app/Contents/MacOS/ykman /usr/local
      sudo install_name_tool -change /Users/travis/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/Python @executable_path/../Frameworks/Python.framework/Versions/3.5/Python ykman-gui/ykman-gui.app/Contents/Resources/qml/io/thp/pyotherside/libpyothersideplugin.dylib
      pkgbuild --install-location /Applications --component ykman-gui/ykman-gui.app yubikey-manager-HEAD-mac.pkg
      rsync yubikey-manager-HEAD-mac.pkg deploy/
    fi

deploy:
  provider: gcs
  access_key_id: "$GCS_ID"
  secret_access_key: "$GCS_KEY"
  bucket: "$GCS_BUCKET"
  skip_cleanup: true
  acl: public-read
  local-dir: "deploy/"
  on:
    condition: $TRAVIS_OS_NAME == osx
