image: Visual Studio 2015

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

install:
  - git submodule update --init --recursive

before_build: 
  - set PATH=%PATH%;C:\Python35\Scripts
  - rm .\vendor\yubikey-manager\ykman\yubicommon
  - xcopy /i /e .\vendor\yubikey-manager\vendor\yubicommon\yubicommon .\vendor\yubikey-manager\ykman\yubicommon
  - C:\Qt\5.7\msvc2015_64\bin\qmake yubikey-manager-qt.pro
  - C:\Qt\Tools\QtCreator\bin\jom

after_build:
  - cd ykman-gui
  - windeployqtqt release\ykman-gui.exe -qmldir=qml
  - cp -r pymodules release\

