# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2015

environment:
  LIBU2F_HOST_VERSION: "1.1.4"
  YKPERS_VERSION: "1.18.1"
  LIBUSB_VERSION: "1.0.21"
  PY_VERSION: "3.6.4"

init:
  # Needed for jom to work.
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  # Add python and Qt to PATH
  - set PATH=C:\Python36;C:\Python36\Scripts;C:\Qt\5.9\msvc2015\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - python --version

install:
  # Submodules are not cloned by default
  - git submodule update --init --recursive
  - choco install swig -y
  - choco upgrade swig

  # Build and install PyOtherSide 
  # Reference: https://pyotherside.readthedocs.io/en/latest/#building-for-windows
  - cd .\vendor\pyotherside
  - ps: (Get-Content .\src\qmldir).replace('pyothersideplugin', 'pyothersideplugin1') | Set-Content .\src\qmldir
  - ps: Clear-Content python.pri
  - ps: Add-Content python.pri "PYTHON_CONFIG = python3-config`nQMAKE_LIBS += -LC:\Python36\libs -lpython36`nQMAKE_CXXFLAGS += -IC:\Python36\include`n"
  - qmake
  - jom
  - jom install
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  # Clean up dirt from installing pyotherside
  - git -C vendor/pyotherside reset --hard
  - git -C vendor/pyotherside clean -dfx

build_script:

  - qmake yubikey-manager-qt.pro
  - qmake -o ykman-gui\Makefile ykman-gui\ykman-gui.pro

  # Fix problem with symbolic link
  - rm .\vendor\yubikey-manager\ykman\yubicommon
  - xcopy /i /e .\vendor\yubikey-manager\vendor\yubicommon\yubicommon .\vendor\yubikey-manager\ykman\yubicommon
  - jom

after_build:

  - ps: wget "https://developers.yubico.com/libu2f-host/Releases/libu2f-host-$env:LIBU2F_HOST_VERSION-win32.zip" -OutFile "libu2f-host-$env:LIBU2F_HOST_VERSION-win32.zip"
  - 7z x libu2f-host-%LIBU2F_HOST_VERSION%-win32.zip -o".\libu2f-host"
  - ps: Copy-Item .\libu2f-host\bin\*.dll .\ykman-gui\release -Force

  - ps: wget "https://developers.yubico.com/yubikey-personalization/Releases/ykpers-$env:YKPERS_VERSION-win32.zip" -OutFile "ykpers-$env:YKPERS_VERSION-win32.zip"
  - 7z x ykpers-%YKPERS_VERSION%-win32.zip -o".\ykpers"
  - ps: Copy-Item .\ykpers\bin\*.dll .\ykman-gui\release -Force 

  - ps: Invoke-WebRequest "http://prdownloads.sourceforge.net/libusb/libusb-$env:LIBUSB_VERSION.7z" -OutFile "libusb-$env:LIBUSB_VERSION.7z" -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
  - 7z x libusb-%LIBUSB_VERSION%.7z -o".\libusb"
  - ps: Copy-Item .\libusb\MS32\dll\*.dll .\ykman-gui\release -Force 

  - ps: wget https://www.python.org/ftp/python/$env:PY_VERSION/python-$env:PY_VERSION-embed-win32.zip -OutFile python-$env:PY_VERSION-embed-win32.zip
  - 7z x python-%PY_VERSION%-embed-win32.zip -o".\ykman-gui\release"
  # Use Qt deployment tool on executable
  - windeployqt .\ykman-gui\release\ykman-gui.exe -qmldir=.\ykman-gui\qml --no-translations --angle --release
  # Add python dependencies to release folder
  - ps: Copy-Item .\ykman-gui\pymodules .\ykman-gui\release -recurse
  # Remove .pyc files from release folder
  - ps: Get-ChildItem -File -Include *.pyc -Recurse | Remove-Item -Force
  - ps: Get-ChildItem -Include __pycache__ -Recurse | Remove-Item -Force
  # Remove .cpp source files
  - ps: Get-ChildItem -Include *.cpp -Recurse | Remove-Item -Force
  # Remove object files
  - ps: Get-ChildItem -Include *.obj -Recurse | Remove-Item -Force
  # Add CLI executable to release folder
  - copy .\ykman-cli\release\ykman.exe .\ykman-gui\release
  # Create zip for deployment
  - 7z a yubikey-manager-qt-%APPVEYOR_REPO_BRANCH%-win.zip .\ykman-gui\release\*
  # Verify that the cli tool can run
  - copy .\ykman-cli\test.py .\ykman-gui\release
  - cd .\ykman-gui\release
  - python test.py
  - cd %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: yubikey-manager-qt-%APPVEYOR_REPO_BRANCH%-win.zip

deploy:
  - provider: S3
    access_key_id: $(AWS_KEY_ID)
    secret_access_key: $(AWS_SECRET_KEY)
    bucket: $(AWS_BUCKET)
    folder: "yubikey-manager-qt"
    region: eu-west-1
    set_public: true
