# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2015

init:
  # Needed for jom to work.
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  # Add python and Qt to PATH
  - set PATH=%PATH%;C:\Python35\Scripts;C:\Qt\5.7\msvc2015\bin;C:\Qt\Tools\QtCreator\bin

install:
  # Submodules are not cloned by default
  - git submodule update --init --recursive
  # Swig needed for pyscard
  - choco install swig -y

before_build:
  # Fix problem with symbolic link
  - rm .\vendor\yubikey-manager\ykman\yubicommon
  - xcopy /i /e .\vendor\yubikey-manager\vendor\yubicommon\yubicommon .\vendor\yubikey-manager\ykman\yubicommon

build_script:
  - qmake yubikey-manager-qt.pro
  - jom

after_build:
  - cd ykman-gui
  # Add libu2f-host
  - mkdir libu2f-host
  - ps: wget https://developers.yubico.com/libu2f-host/Releases/libu2f-host-1.1.3-win32.zip -OutFile libu2f-host-1.1.3-win32.zip
  - 7z x libu2f-host-1.1.3-win32.zip -o".\libu2f-host"
  - robocopy "libu2f-host\bin" ".\release" *.dll
  # Add embedded python
  - ps: wget https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-win32.zip -OutFile python-3.5.2-embed-win32.zip
  - 7z x python-3.5.2-embed-win32.zip -o".\release"
  # Add msvcp140.dll
  - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvcp140.dll" ".\release"
  # Add .dlls for redistrubution, see https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/
  - xcopy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86" ".\release"
  # Use Qt deployment tool on executable
  - windeployqt release\ykman-gui.exe -qmldir=qml
  # Add python dependencies to release folder
  - cp -r pymodules release\

