image: Visual Studio 2015

before_build: 
  - C:\Qt\5.7\msvc2015_64\bin\qmake yubikey-manager-qt.pro
  - C:\Qt\5.7\msvc2015_64\bin\jom

after_build:
  - cd ykman-gui
  - windeployqtqt release\ykman-gui.exe -qmldir=qml
  - cp -r pymodules release\

