# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2015

init:
  # Needed for jom to work.
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  # Add python and Qt to PATH
  - set PATH=%PATH%;C:\Python35\Scripts;C:\Qt\5.7\msvc2015\bin;C:\Qt\Tools\QtCreator\bin

install:
  # Submodules are not cloned by default
  - git submodule update --init --recursive
  # Swig needed for pyscard
  - ps: wget http://freefr.dl.sourceforge.net/project/swig/swigwin/swigwin-3.0.10/swigwin-3.0.10.zip -OutFile swigwin-3.0.10.zip
  - 7z x swigwin-3.0.10.zip
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\swigwin-3.0.10

before_build:
  # Fix problem with symbolic link
  - rm .\vendor\yubikey-manager\ykman\yubicommon
  - xcopy /i /e .\vendor\yubikey-manager\vendor\yubicommon\yubicommon .\vendor\yubikey-manager\ykman\yubicommon

build_script:
  - qmake yubikey-manager-qt.pro
  - jom

after_build:
  # Add libu2f-host
  - mkdir libu2f-host
  - ps: wget https://developers.yubico.com/libu2f-host/Releases/libu2f-host-1.1.3-win32.zip -OutFile libu2f-host-1.1.3-win32.zip
  - 7z x libu2f-host-1.1.3-win32.zip -o".\libu2f-host"
  # robocopy has wierd exit codes, needs to be silenced.
  - robocopy "libu2f-host\bin" ".\ykman-gui\release" *.dll ^& IF %ERRORLEVEL% LEQ 1 exit 0
  # Add embedded python
  - ps: wget https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-win32.zip -OutFile python-3.5.2-embed-win32.zip
  - 7z x python-3.5.2-embed-win32.zip -o".\ykman-gui\release"
  # Add msvcp140.dll
  - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvcp140.dll" ".\ykman-gui\release"
  # Add .dlls for redistrubution, see https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/
  - xcopy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86" ".\ykman-gui\release"
  # Use Qt deployment tool on executable
  - windeployqt .\ykman-gui\release\ykman-gui.exe -qmldir=qml
  # Add python dependencies to release folder
  - xcopy /i /e .\ykman-gui\pymodules .\ykman-gui\release
  # Add CLI executable to release folder
  - copy .\ykman-cli\release\ykman.exe .\ykman-gui\release

artifacts:
  - path: .\ykman-gui\release
  - name: yubikey-manager-win

deploy:
 - provider: S3
  access_key_id: %AWS_KEY_ID%
  secret_access_key: %AWS_SECRET_KEY%
  bucket: %AWS_BUCKET%
  region: eu-west-1
  set_public: true
  artifact: yubikey-manager-win
